# Generated by Django 3.1.7 on 2021-10-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_objects', '0003_auto_20211011_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='longittude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='sportzone',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_objects.position'),
        ),
    ]
