# Generated by Django 3.1.7 on 2021-10-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_objects', '0006_auto_20211014_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportzone',
            name='open_type',
        ),
        migrations.AddField(
            model_name='sportzone',
            name='open_type',
            field=models.ManyToManyField(null=True, to='sport_objects.OpenedType'),
        ),
    ]
