# Generated by Django 3.1.7 on 2021-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport_objects', '0005_sportzone_zone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sport_zones', models.ManyToManyField(to='sport_objects.SportZone')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_objects', models.ManyToManyField(to='sport_objects.SportZone')),
                ('groups', models.ManyToManyField(to='map_operations.Group')),
            ],
        ),
    ]
